receivers:
  prometheusremotewrite:
    endpoint: 0.0.0.0:19291
    path: /api/v1/write

processors:
  resource/neck:
    attributes:
      - key: encore.app_id
        value: ${env:APP_ID}
        action: upsert
      - key: deployment.environment
        value: ${env:APP_ENV}
        action: upsert
  batch:
    timeout: 5s
    send_batch_size: 10000

exporters:
  otlphttp/signoz:
    endpoint: ${env:SIGNOZ_OTLP_HTTP_ENDPOINT}

service:
  telemetry:
    logs:
      level: warn
  pipelines:
    metrics:
      receivers: [prometheusremotewrite]
      processors: [resource/neck, batch]
      exporters: [otlphttp/signoz]
